extends:
  - stylelint-config-standard
  - stylelint-config-html
  - stylelint-config-tailwindcss
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - variants
        - responsive
        - screen
  color-function-notation: null
  declaration-block-trailing-semicolon:
  no-descending-specificity:

ignoreFiles:
  - public/**
  - resources/**
  - static/**
  - layouts/partials/{css,imgh}.html
