version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    container_name: modern-resume-theme
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll