demosite = "https://cjshearer.github.io/modern-hugo-resume/"
description = "A responsive, minimal, print-friendly resume builder"
homepage = "https://github.com/cjshearer/modern-hugo-resume"
license = "MIT"
licenselink = "https://github.com/cjshearer/modern-hugo-resume/main/LICENSE"
name = "modern-hugo-resume"
tags = ["responsive", "minimal", "light", "dark", "dak mode"]

[author]
homepage = "https://cjshearer.dev"
name = "Cody Shearer"

[module]
  [module.hugoVersion]
  extended = true
  min = "0.116.3"

  [[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
    [[module.imports.mounts]]
    source = "svgs"
    target = "assets/svgs"
