demosite = "https://cjshearer.github.io/modern-hugo-resume/"
description = "A responsive, minimal, print-friendly resume builder"
homepage = "https://github.com/cjshearer/modern-hugo-resume"
license = "MIT"
licenselink = "https://github.com/cjshearer/modern-hugo-resume/main/LICENSE"
name = "modern-hugo-resume"
tags = ["responsive", "minimal", "light", "dark", "dak mode"]

[author]
homepage = "https://cjshearer.dev"
name = "Cody Shearer"
