name: Setup Runner
description: Install dependencies shared by all jobs
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v12
    - uses: DeterminateSystems/magic-nix-cache-action@v7
