on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-runner
      - name: Build
        run: pnpm build
      - if: github.ref == 'refs/heads/main'
        name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: build
          path: build
          retention-days: 1
