on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-runner
      - name: Build
        run: pnpm build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1
