on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-runner
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build
        run: nix build
      - if: github.ref == 'refs/heads/main'
        name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: build
          path: result
          retention-days: 1
