on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-runner
      - name: Check Linting and Formatting
        shell: bash
        run: nix develop .#default --command bash -c "pnpm format:check && pnpm lint"
